server:
  port: 8077
#配置数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: Yy1023349104
mybatis:
  config-location: classpath:static/mybatis/mybatis-config.xml
  mapper-locations: mapper/mapper.xml
  type-aliases-package: com.program.domain.Program
logging:
  level:
    root: debug
#  设置日志的级别

